### ISSUE TITLE
function setUrl from L.ImageOverlay does not work

### ISSUE THREAD

**Issue by hmesa** [IvanSanchez/Leaflet.ImageOverlay.Rotated#1]
Hi, I tried to change the url from an ImageOverlay.Rotated 
`myOverlay.setUrl(newUrl)`
but it did not work. Maybe extending the function `setUrl` to 
`setUrl:function(url){`
`  this._super(url);` 
`  this._rawImage.src=url`; 
`}`
could be enough.
A very good and useful job, by the way. Thank you very much
  Best regards

**Comment by IvanSanchez** [comment]
#2 should fix this. Can you please test that out?

**Comment by hmesa** [comment]
Everything seems to work fine now, thanks

**Comment by oubaguilai** [comment]
@hmesa  Hi , I tried to change the url from an ImageOverlay myOverlay.setUrl(newUrl)
but it did not work ，can you tell me how to resolve?

**Comment by thanh-taro** [comment]
It seems to be missing `setUrl` in the newest release.

**Comment by hmesa** [comment]
Hi, try adding the following code to the L.ImageOverlay.Rotated class
setUrl : function(url) {
        this._url = url;
        if (this._rawImage) {
            this._rawImage.src = url;
        }
        return this;
    }

**Comment by thanh-taro** [comment]
Yeah. It’s a workaround solution. But it’ll be better if the owner add it back to source code.

**Comment by hmesa** [comment]
The author made the change but i thing he did it on a branch. He only needs to merge it to master when he will have time.
  Bests

**Comment by thanh-taro** [comment]
Yeah. I saw the pull request. 10 months ago. :(

**Comment by IvanSanchez** [comment]
OK, OK, you got it. Merged, version bumped, and published into `npm`.

**Comment by thanh-taro** [comment]
Great! Thank you. :D
