### ISSUE TITLE
How to use with React.js

### ISSUE THREAD

**Issue by mottab** [IvanSanchez/Leaflet.ImageOverlay.Rotated#10]
I wonder how can I use this module with [react-leaflet](https://github.com/PaulLeCam/react-leaflet)
Any working example of that?

Thanks

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
