### ISSUE TITLE
Can't set default zoom, Is it a bug?

### ISSUE THREAD

**Issue by weixu2015** [IvanSanchez/Leaflet.ImageOverlay.Rotated#11]
I can't set the default zoom when use this plugin.
I tried all kings of methods to set zoom,like setZoom(11), map.setView([xx,xx], 11)....
Please help me.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by weixu2015** [comment]
This is an example which shows that problem:
https://codepen.io/davidbrave/project/full/XLkmNk

I set the default zoom by code:
var map = new L.Map('map', {
    center: [40.52130361585499, -3.775139721987811],
    zoom: 12
});
but the map shows zoom 19 (console.log(map._zoom)) when put the phone image on it.
The acutual default zoom is not certain ,maybe other number, but it hardly be the zoom number I set default.

**Comment by IvanSanchez** [comment]
The call to `fitBounds()` is still there. Not a Leaflet.ImageOverLay.Rotated bug.

**Comment by weixu2015** [comment]
Thanks
