### ISSUE TITLE
Intergrating with Path transform (2nd try..._)

### ISSUE THREAD

**Issue by cubecleveland** [IvanSanchez/Leaflet.ImageOverlay.Rotated#17]
Sorry for the blurry question :)

Library is working great, but we would like to Add a  dragging capability for the entire layer.

I'm using leaflet Path transform library to edit and drag shapes 
https://github.com/w8r/Leaflet.Path.Transform

Library allows to transform and drag polygon shapes on the screen.
It seems like a natural combo with your library since if I'm not mistaken the dragging feature is not available yet via your library.

1) Question is: is there any know code  snippest to integrate the 2 libraries,
2) If not, is there any simple way we can extend your library to support dragging as well ?

If u can give us some pointers that would be great

**Comment by IvanSanchez** [comment]
So, follow-up from #16, I guess.

>    Question is: is there any know code snippest to integrate the 2 libraries,

It's spelt ["snippet"](https://www.merriam-webster.com/dictionary/snippet) and, to my knowledge, there is not.

>    If not, is there any simple way we can extend your library to support dragging as well ?

I don't think so. The design was focused on display (based on lat-lng), not interaction (based on screen pixel coordinates).

> If u can give us some pointers that would be great

Read the code. Understand the architecture. Scratch your own itch.
